Organizations:
    - &Org6
        Name: Org6MSP

        ID: Org6MSP

        MSPDir: crypto-config/peerOrganizations/org6.example.com/msp

        AnchorPeers:
            - Host: peer0.org6.example.com
              Port: 17051