
version: '3.2'

networks:
    skcript:
        external: 
            name: skcript

services:

    peer0_org6:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ${ORG_HOSTNAME}
        image: hyperledger/fabric-peer:latest
        hostname: peer0.org6.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=skcript
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=skcript
            - CORE_PEER_ADDRESSAUTODETECT=true
            # - CORE_PEER_GOSSIP_ORGLEADER=false
            # - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_PROFILE_ENABLED=true
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_LOGGING_LEVEL=CRITICAL
            - CORE_LOGGING_GOSSIP=true
            - CORE_LOGGING_MSP=CRITICAL
            # - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            # TLS settings
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org6.example.com:17052
            - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org6.example.com/tls/ca.crt
            - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org6.example.com/tls/client.crt
            - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org6.example.com/tls/client.key
            - CORE_PEER_LISTENADDRESS=0.0.0.0:17051
            - CORE_PEER_ID=peer0.org6.example.com
            - CORE_PEER_ADDRESS=peer0.org6.example.com:17051
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${ORG_IP}:17051
            - CORE_PEER_LOCALMSPID=Org6MSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0_org6:5984
        volumes:
            - /var/run/:/host/var/run/
            # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
            # - ../crypto-config/:/var/hyperledger/config
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org6.example.com/peers/peer0.org6.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org6.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        depends_on:
            - couchdb0
        networks:
          skcript:
            aliases:
                - peer0.org6.example.com
        ports:
          - 17051:17051
          - 17053:17053

    peer1_org6:
        deploy:
            replicas: 1
            restart_policy:
                condition: on-failure
                delay: 5s
                max_attempts: 3
            placement:
                constraints:
                    - node.hostname == ${ORG_HOSTNAME}
        image: hyperledger/fabric-peer:latest
        hostname: peer1.org6.example.com
        environment:
            - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
            - CORE_PEER_NETWORKID=skcript
            - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=skcript
            - CORE_PEER_ADDRESSAUTODETECT=true
            # - CORE_PEER_GOSSIP_ORGLEADER=false
            # - CORE_PEER_GOSSIP_USELEADERELECTION=true
            - CORE_PEER_PROFILE_ENABLED=true
            #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
            - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            - CORE_LOGGING_LEVEL=CRITICAL
            - CORE_LOGGING_GOSSIP=true
            - CORE_LOGGING_MSP=CRITICAL
            # - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
            # TLS settings
            - CORE_PEER_TLS_ENABLED=false
            - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
            - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
            - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
            - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
            - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org6.example.com:18052
            - CORE_PEER_ID=peer1.org6.example.com
            - CORE_PEER_ADDRESS=peer1.org6.example.com:18051
            - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org6.example.com/tls/ca.crt
            - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org6.example.com/tls/client.crt
            - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org6.example.com/tls/client.key
            - CORE_PEER_GOSSIP_EXTERNALENDPOINT=${ORG_IP}:18051
            - CORE_PEER_LISTENADDRESS=0.0.0.0:18051
            - CORE_PEER_LOCALMSPID=Org6MSP
            - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
            - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_org6:5984
        volumes:
            - /var/run/:/host/var/run/
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org6.example.com/peers/peer1.org6.example.com/msp:/var/hyperledger/msp
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org6.example.com/peers/peer1.org6.example.com/tls:/var/hyperledger/tls
            - /var/mynetwork/certs/crypto-config/peerOrganizations/org6.example.com/users:/var/hyperledger/users
            - /var/mynetwork/certs/config/:/var/hyperledger/config
        command: peer node start
        working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        depends_on:
            - couchdb0
        ports:
          - 18051:18051
          - 18053:18053
        networks:
          skcript:
            aliases:
                - peer1.org6.example.com
