
version: '3.2'

networks:
  skcript:
    external: 
      name: skcript

services:

  peer0_org4:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == $ORG4_HOSTNAME
    image: hyperledger/fabric-peer:latest
    hostname: peer0.org4.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=skcript
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=skcript
      - CORE_PEER_ADDRESSAUTODETECT=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
      - CORE_LOGGING_LEVEL=CRITICAL
      - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
      - CORE_LOGGING_MSP=CRITICAL
      # - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      # TLS settings
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_CHAINCODELISTENADDRESS=peer0.org4.example.com:13052
      - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org4.example.com/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org4.example.com/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org4.example.com/tls/client.key
      - CORE_PEER_ID=peer0.org4.example.com
      - CORE_PEER_ADDRESS=peer0.org4.example.com:13051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=34.208.11.1:13051
      - CORE_PEER_LISTENADDRESS=0.0.0.0:13051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb0_org4:5984
    volumes:
      - /var/run/:/host/var/run/
      # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
      # - ../crypto-config/:/var/hyperledger/config
      - /var/mynetwork/certs/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/msp:/var/hyperledger/msp
      - /var/mynetwork/certs/crypto-config/peerOrganizations/org4.example.com/peers/peer0.org4.example.com/tls:/var/hyperledger/tls
      - /var/mynetwork/certs/crypto-config/peerOrganizations/org4.example.com/users:/var/hyperledger/users
      - /var/mynetwork/certs/config/:/var/hyperledger/config
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb0
    networks:
      skcript:
        aliases:
          - peer0.org4.example.com
    ports:
      - 13051:13051
      - 13053:13053
      
  peer1_org4:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
      placement:
        constraints:
          - node.hostname == $ORG4_HOSTNAME
    image: hyperledger/fabric-peer:latest
    hostname: peer1.org4.example.com
    environment:
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - CORE_PEER_NETWORKID=skcript
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=skcript
      - CORE_PEER_ADDRESSAUTODETECT=true
      # - CORE_PEER_GOSSIP_ORGLEADER=false
      # - CORE_PEER_GOSSIP_USELEADERELECTION=true
      - CORE_PEER_PROFILE_ENABLED=true
      - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      #- CORE_LEDGER_STATE_STATEDATABASE=LevelDB
      - CORE_LOGGING_LEVEL=CRITICAL
      - CORE_LOGGING_GOSSIP=${CORE_LOGGING_GOSSIP}
      - CORE_LOGGING_MSP=CRITICAL
      # - CORE_PEER_MSPCONFIGPATH=/var/hyperledger/msp
      # TLS settings
      - CORE_PEER_TLS_ENABLED=false
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED=false
      - CORE_PEER_TLS_CERT_FILE=/var/hyperledger/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/var/hyperledger/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/var/hyperledger/tls/ca.crt
      - CORE_PEER_CHAINCODELISTENADDRESS=peer1.org4.example.com:14052
      - CORE_PEER_ID=peer1.org4.example.com
      - CORE_PEER_ADDRESS=peer1.org4.example.com:14051
      - ORDERER_TLS_CLIENTROOTCAS_FILES=/var/hyperledger/users/Admin@org4.example.com/tls/ca.crt
      - ORDERER_TLS_CLIENTCERT_FILE=/var/hyperledger/users/Admin@org4.example.com/tls/client.crt
      - ORDERER_TLS_CLIENTKEY_FILE=/var/hyperledger/users/Admin@org4.example.com/tls/client.key
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=34.208.11.1:14051
      - CORE_PEER_LOCALMSPID=Org4MSP
      - CORE_PEER_LISTENADDRESS=0.0.0.0:14051
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdb1_org4:5984
    volumes:
      - /var/run/:/host/var/run/
      # - $GOPATH/src/github.com/hyperledger/fabric/:/opt/gopath/src/github.com/hyperledger/fabric/
      # - ../crypto-config/:/var/hyperledger/config
      - /var/mynetwork/certs/crypto-config/peerOrganizations/org4.example.com/peers/peer1.org4.example.com/msp:/var/hyperledger/msp
      - /var/mynetwork/certs/crypto-config/peerOrganizations/org4.example.com/peers/peer1.org4.example.com/tls:/var/hyperledger/tls
      - /var/mynetwork/certs/crypto-config/peerOrganizations/org4.example.com/users:/var/hyperledger/users
      - /var/mynetwork/certs/config/:/var/hyperledger/config
    command: peer node start
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    depends_on:
      - couchdb0
    ports:
      - 14051:14051
      - 14053:14053
    networks:
      skcript:
        aliases:
          - peer1.org4.example.com
