# Generated by Django 2.2.2 on 2019-06-12 06:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_cert_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='location',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
