# Generated by Django 2.2.2 on 2019-06-12 06:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0004_cert_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='org',
            field=models.CharField(default=django.utils.timezone.now, max_length=256),
            preserve_default=False,
        ),
    ]
