# Generated by Django 2.2.2 on 2019-06-12 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_cert_org'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
