# Generated by Django 2.2.2 on 2019-06-12 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_cert_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='cert',
            name='duration',
            field=models.CharField(default='', max_length=100),
        ),
    ]
