# Generated by Django 2.2.2 on 2019-06-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_cert_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cert',
            old_name='duration',
            new_name='time_till',
        ),
    ]
