# Generated by Django 2.2.2 on 2019-06-12 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_auto_20190612_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='time_till',
            field=models.DateTimeField(default='', max_length=100),
        ),
    ]
