# Generated by Django 2.2.2 on 2019-06-12 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_auto_20190612_0758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cert',
            name='time_till',
            field=models.DateTimeField(),
        ),
    ]
