# Generated by Django 2.1.2 on 2018-12-30 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_adfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfile',
            name='bg_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='adfile',
            name='text_color',
            field=models.CharField(blank=True, default='', max_length=7),
        ),
    ]
