# Generated by Django 2.1.2 on 2018-12-30 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181230_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adfile',
            name='text',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
