# Generated by Django 2.2.2 on 2019-06-11 23:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20181230_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dob',
            field=models.DateField(default=datetime.date(2000, 1, 1)),
        ),
    ]
