# Generated by Django 2.2.2 on 2019-06-12 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_profile_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_org',
            field=models.BooleanField(default=False),
        ),
    ]
